# BMH Edge Spring Boot

# Google Text - To -Speech

The following environment variable is required for Google API authentication: 

GOOGLE_APPLICATION_CREDENTIALS=<credentials>.json 

The BMH-EDGE-GOOGLE.zip file contains an example Google API credential file for demo purposes.   
Please contact the BMH-EDGE development team for password information.  

# Spring Boot Debugging
https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-debug.html


# Spring Web
https://spring.io/guides/gs/serving-web-content/

## How to build
From ~/parent

mvn clean install

## How to run

## remote run (assuming remote host is bmh2)  
    mvn spring-boot:run -Dspring-boot.run.profiles=prod
 
## local run
    mvn spring-boot:run -Dspring-boot.run.profiles=dev
    
    
## Under Development ##

## To get info about the routes

To show a summary of all the routes

----
curl -XGET -s http://localhost:8080/camel/routes
----

To show detailed information for a specific route

----
curl -XGET -s http://localhost:8080/camel/routes/{id}/info
----

View BMH Status
----
http://localhost:8080/bmh/status
http://localhost:8080/bmh/playlist
----


## More information

You can find more information about Apache Camel at the website: http://camel.apache.org/
