# the name of Camel
camel:
  springboot:
    name: BMHEDGE
    path: /bmh
    
# configure h2 web service (http://localhost:8080/h2-console)
spring:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

# to automatic shutdown the JVM after a period of time
#camel.springboot.duration-max-seconds=60
#camel.springboot.duration-max-messages=100

# add for example: &repeatCount=5 to the timer endpoint to make Camel idle
#camel.springboot.duration-max-idle-seconds=15

# properties used in the Camel route and beans
# --------------------------------------------
bmh:
  qpid_host: localhost
  queue: ingest

# how often to trigger the timer
timer:
  period: 2000
  
component:
    servlet:
      mapping:
        contextPath: /bmh/*
       

# all access to actuator endpoints without security
management:
  address: 0.0.0.0
  port: 8081
  security:
    enabled: false
# turn on actuator health check
endpoints:
  enabled: true
  health:
    enabled: true
  camelroutes:
    enabled: true
    read-only: true
    
# to configure logging levels
logging:
  file: logs/bmh_edge.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
#logging.level.org.springframework = INFO
#logging.level.org.apache.camel.spring.boot = INFO
#logging.level.org.apache.camel.impl = DEBUG
#logging.level.sample.camel = DEBUG