# the name of Camel
name: BMHEDGE-PROD
environment: prod
camel:
  springboot:
    name: BMHEDGE
    path: /bmh
    
# configure h2 web service (http://localhost:8080/h2-console)
spring:
  profiles: prod
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
google:
  speech:
    apikey: /home/amoran/Git/bmh-edge/bmh-edge-spring-boot/BMH-EDGE-7fbcada789e1.json
    dir: /tmp
    

# to automatic shutdown the JVM after a period of time
#camel.springboot.duration-max-seconds=60
#camel.springboot.duration-max-messages=100

# add for example: &repeatCount=5 to the timer endpoint to make Camel idle
#camel.springboot.duration-max-idle-seconds=15

# properties used in the Camel route and beans
# --------------------------------------------
bmh:
  qpid:
    host: bmh2
    queue: BMH.EDGE
  transmitter:
    id: HGR
    lineOut: hw:1

# how often to trigger the timer
timer:
  period: 2000
  
component:
    servlet:
      mapping:
        contextPath: /bmh/*
       

# all access to actuator endpoints without security
management:
  address: 0.0.0.0
  port: 8081
  security:
    enabled: false
# turn on actuator health check
endpoints:
  enabled: true
  health:
    enabled: true
  camelroutes:
    enabled: true
    read-only: true
    
# to configure logging levels
logging:
  file: logs/bmh_edge.log
  pattern:
    console: "%d [%-20.20thread] %-5level %logger : %msg%n"
    file: "%d [%-20thread] %-5level %logger : %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
    com.google: INFO
    org.apache.camel: INFO
    gov.noaa.nws: INFO
    org.springframework.aop.interceptor.PerformanceMonitorInterceptor: TRACE
#logging.level.org.springframework = INFO
#logging.level.org.apache.camel.spring.boot = INFO
#logging.level.org.apache.camel.impl = DEBUG
#logging.level.sample.camel = DEBUG
#logging.level.sample.camel = DEBUG
